name: CRM Website Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: |
          npm install
        working-directory: tests/unit

      - name: Run Jest Unit Tests
        run: |
          npm run test-unit
        working-directory: tests/unit

      - name: ESLint
        run: |
          npm run lint
        working-directory: tests/unit  # Assuming your ESLint config is in tests/unit

      - name: Upload Test Results
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-results-${{ github.sha }}
          path: tests/unit/src/junit.xml
